### ISSUE TITLE
Any way to indicate that a path is optional?

### ISSUE THREAD

**Issue by grofit** [perrin4869/gulp-xml-transformer#2]
Currently I am trying to use this as part of a build script where I want to basically read some environmental config files and for any correlating `appSetting` or `connectionString` nodes in a `web/app.config` file replace them.

The problem is there will probably be a lot of environmental variables which are not going to be in the web.config files and currently it reports an error that it cannot find the path, so is there a way for me to build all possible paths but indicate that if it doesn't find a match just skip it and continue? 

== Edit

It seems like https://github.com/perrin4869/gulp-xml-transformer/blob/master/src/transformers.js#L21 could be updated in some way to basically check for an `isRequired` property or something, but let me know your thoughts on it.

**Comment by perrin4869** [comment]
An `isRequired` option sounds great! Not sure what the default value for it should be though. For compatibility's sake, maybe `true` would be better... but I have a feeling that `false` makes more sense.
A PR would be appreciated :D

**Comment by grofit** [comment]
I would love to but I am currently up against it for a release, had to drop the xml transform for the moment and look at something else, but if I get time to play some tech debt I will look back into this, but I wouldn't see that as a guarantee it will be done anytime soon.

**Comment by grofit** [comment]
Did convince team to give me 30 mins to try and get it fixed, but problem is I cannot build it due to lint not liking windows CRLF stuff and also dont have python installed and as mad as it may sound I dont have admin rights on this PC so cannot get the xml thingy compiled.

I did however prototype the change, but haven't put a test in:
https://gist.github.com/grofit/a18b872245f5b217c9125faee658181f

If you get time have a quick look over and if you are happy enough with it and can put a test in to verify it matches the behaviour you can put it into a commit etc, otherwise it will be next week before I will be able to look at it again.

**Comment by perrin4869** [comment]
@grofit thank you for your input!
I just pushed https://github.com/perrin4869/gulp-xml-transformer/commit/33a7ed8dcf7ec06a5286e5940d93914a7b37a4d0
After the Travis passes my tests I'll publish a new version to npm.
Tell me if this solves your problem!

**Comment by perrin4869** [comment]
Released in `1.3.0`

**Comment by grofit** [comment]
Thanks for sorting it :)
