### ISSUE TITLE
Any way to ignore non xml files in a stream?

### ISSUE THREAD

**Issue by grofit** [perrin4869/gulp-xml-transformer#3]
So I have a weird scenario where I need to:

- Crack open a zip file
- Transform some xml files in there
- Re-zip up the file
- Output it somewhere

Problem is I will have a stream which will contain a myriad of files with only some being XML, so is there a way to be able to infer to it a filter of files to process, or some way for it to just bypass any non xml files in the stream?

**Comment by perrin4869** [comment]
hm... wouldn't [gulp-filter](https://www.npmjs.com/package/gulp-filter) work?
Not sure this is an issue with this module

**Comment by perrin4869** [comment]
oh, you could try [gulp-if](https://github.com/robrich/gulp-if) too

**Comment by grofit** [comment]
Yeah I didn't realise I could restore the stream so I was able to use gulp filter, will close this issue.

**Comment by perrin4869** [comment]
I would recommend you check out gulp-if too, might fit your use case here more :)
